---
title: "Introducing The Army to Tidymodels"
author: "Dusty Turner and Max Kuhn"
date: "11/6/2019"
output: html_document
---

## Call Libraries and set preferences

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(tidymodels)
library(skimr)
options(tibble.width = Inf)
```

## Read in and manipulate data

```{r read and manipulate}
rawdata = read_csv("aircraft.csv") %>%
  janitor::clean_names() %>%
  sample_n(1000) %>%
  select(-c(gain_loss,service_term_date,util_code,nmcs_org_percent, nmcs_spt_percent, nmcm_equip_percent, pmcs_org_percent, pmcs_spt_percent, pmcm_org_percent, pmcm_spt_percent,ric,asset_type)) %>%
  mutate(as_of_date = mdy(as_of_date)) %>%
  mutate(niin = as.factor(niin)) %>% 
  mutate(present_location = if_else(is.na(present_location),"unknown",present_location)) 

skim(rawdata)
```

## Identify Missing Data

```{r}
skimr::skim(rawdata) %>% as_tibble() %>%
  select(skim_variable, n_missing) %>%
  filter(n_missing>0)

library(Amelia)
missmap(rawdata)
```


## Split, Prepare, and Inpute Data
```{r}
data = rawdata

data_split = data %>% initial_split(prop = .6)

# data_split %>%
#   training()
# data_split %>%
#   testing()

flight_recipe = 
data_split %>%
  training() %>%
  recipe(hours_flown ~ .) %>%
  recipes::step_meanimpute(
    age_years_by_accept_date, fmc_percent,nmcs_percent, mc_percent,nmcm_org_percent,
    nmcm_percent,nmcm_spt_percent, nmcm_depot_percent,pmc_percent,pmcs_percent,
    pmcm_percent
    ) %>%
  step_modeimpute(uessr, army_accept_date) %>%
  step_corr(
    age_years_by_accept_date, fmc_percent,nmcs_percent,mc_percent,nmcm_org_percent,
    nmcm_percent,nmcm_spt_percent, nmcm_depot_percent,pmc_percent,pmcs_percent,
    pmcm_percent
    ) %>%
  step_center(
    age_years_by_accept_date, fmc_percent,nmcs_percent,nmcm_org_percent,
    nmcm_percent,nmcm_spt_percent, nmcm_depot_percent,pmc_percent,pmcs_percent,
    pmcm_percent
    ) %>%
  step_scale(
    age_years_by_accept_date, fmc_percent,nmcs_percent,nmcm_org_percent,
    nmcm_percent,nmcm_spt_percent, nmcm_depot_percent,pmc_percent,pmcs_percent,
    pmcm_percent
  ) %>%
  prep()
```

## Build Models
```{r}
flight_testing = flight_recipe %>%
  bake(training(data_split)) 

flight_training = juice(flight_recipe)

flight_ranger = 
  rand_forest(trees = 100, mode = "regression") %>%
  set_engine("ranger") %>%
  fit(hours_flown ~ ., data = flight_training)

flight_rf = 
  rand_forest(trees = 100, mode = "regression") %>%
  set_engine("randomForest") %>%
  fit(hours_flown ~ ., data = flight_training)

flight_lm = 
  linear_reg(mode = "regression") %>%
  set_engine("lm") %>%
  fit(hours_flown ~ ., data = flight_training)

flight_lasso = 
  linear_reg(mode = "regression") %>%
  set_engine("glmnet") %>%
  fit(hours_flown ~ ., data = flight_training)
```

## Make Predictions and Test Models
```{r}
flight_testing %>%
  select(hours_flown) %>%
  bind_cols(
    predict(flight_ranger, flight_testing) %>% rename(ranger_pred = .pred),
    predict(flight_rf, flight_testing) %>% rename(rf_pred = .pred),
    predict(flight_lm, flight_testing) %>% rename(lm_pred = .pred),
    predict(flight_lasso, flight_testing, penalty = 10) %>% rename(lasso_pred = .pred),
  ) %>%
  pivot_longer(cols = -hours_flown) %>%
  rename(model = name, prediction = value) %>%
  group_by(model) %>%
  metrics(truth = hours_flown, estimate = prediction) %>% 
  select(-.estimator) %>% 
  pivot_wider(names_from = .metric, values_from = .estimate) %>%
  arrange(rmse)
```

Better said, tidymodels provides a single set of functions and arguments to define a model. It then fits the model against the requested modeling package.
